# Generated by Django 6.1.1 on 2026-09-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_field', models.BooleanField(default=True, help_text='Operational site (True) vs office / analytical unit (False)')),
                ('is_active', models.BooleanField(default=True)),
                ('organisational_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_units', to='orgref.organisationalstructure')),
            ],
        ),
    ]
