# Generated by Django 6.1.1 on 2026-09-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CMMS family code <class>_<type>', max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sce', models.BooleanField(default=False, help_text='Safety & environmentally critical by default')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Section categories',
            },
        ),
        migrations.CreateModel(
            name='SystemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'System classes',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CMMS asset code. Not unique across tenants!', max_length=64)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systemref.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='SystemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Also the CMMS asset code of the platform', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, help_text='Decommissioning date', null=True)),
                ('source', models.CharField(default='MDM', max_length=64)),
                ('org_unit', models.ForeignKey(help_text='Site (CMMS body)', on_delete=django.db.models.deletion.PROTECT, related_name='system_units', to='orgref.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CMMS asset code (SYS_…). Not unique across tenants!', max_length=64)),
                ('tag', models.CharField(help_text='Functional name', max_length=255)),
                ('source', models.CharField(help_text='Origin tenant, e.g. GLOBAL or LATAM', max_length=64)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systemref.sectioncategory')),
                ('system_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systemref.systemclass')),
                ('system_unit', models.ForeignKey(help_text='Platform the system belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='systemref.systemunit')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAttributeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='systemref.system')),
                ('system_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemref.systemattribute')),
            ],
            options={
                'unique_together': {('system', 'system_attribute')},
            },
        ),
        migrations.CreateModel(
            name='SystemEquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_assignments', to='systemref.equipment')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='systemref.system')),
            ],
            options={
                'unique_together': {('system', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='SystemUnitToSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('section_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemref.sectioncategory')),
                ('system_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='systemref.systemunit')),
            ],
            options={
                'unique_together': {('system_unit', 'section_category')},
            },
        ),
    ]
